# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7610810742a88e8a4c8feb80d2869966b77366012b3616167a8ceb8c7082d8e2b2bfafbef7bae2fd3c3378eceb294a29ef24287606fe0fc57b3eaac6a320ce4

test:
  secret_key_base: 1b10e6ec8b8ab0fb1ba961abf2df7cdfbce587417fe66a5473115193904c5d4189b0737dfdb4fadcbb6a1316a7c1b2cf19f777bbbf291607ec237864ca878971

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
